### ISSUE TITLE
Changing tab color fails

### ISSUE THREAD

**Issue by anakinsleftleg** [mondersky/tabscolor-vscode#2]
It gives me a notification that says Tabscolor was unable to patch your VS Code Files. There is no error output in the OUTPUT window.

**Comment by anakinsleftleg** [comment]
I find this in the OUTPUT actually:

```output
[2022-07-01 18:55:26.986] [exthost] [warning] TextEditor is closed/disposed
[2022-07-01 18:56:23.584] [exthost] [error] TypeError: Cannot read properties of undefined (reading 'document')
    at c:\Users\Jeremiah\.vscode\extensions\mondersky.tabscolor-0.1.4-win32-x64\extension.js:454:45
    at o._executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:62521)
    at o.$executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:63225)
    at s._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:86:13828)
    at s._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:86:13512)
    at s._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:86:12173)
    at s._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:86:10843)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:86:8949
    at g.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
    at b.deliver (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:2265)
    at v.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1843)
    at a.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:19025)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:34863
    at g.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
    at b.deliver (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:2265)
    at v.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1843)
    at a.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:19025)
    at r._receiveMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:23606)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:21140
    at g.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
    at b.deliver (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:2265)
    at v.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1843)
    at v.acceptChunk (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:15856)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:14986
    at Socket.R (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:13798)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23) tabscolor.salmon {"value":"mondersky.tabscolor","_lower":"mondersky.tabscolor"}
[2022-07-01 18:56:34.989] [exthost] [warning] TextEditor is closed/disposed
[2022-07-01 18:56:35.112] [exthost] [info] ExtensionService#_doActivateExtension bungcip.better-toml, startup: false, activationEvent: 'onLanguage:toml
```

**Comment by KaDw** [comment]
I also experience similar issue, I'm using Ubuntu 20.04, the message for me is:
```
Tabscolor was unable to write to /snap/code/99/usr/share/code/resources/app/out/bootstrap-window.js
```

**Comment by pinty** [comment]
I also get the same error "`Tabscolor was unable to patch your VS Code files.`" whenever I try to apply a color to any of my opened tabs. Looking into the extension properties > runtime status there seems to be one error popping up:
`EPERM: operation not permitted, open 'c:\Program Files\VSCodium\resources\app\out\bootstrap-window.js'`

**Comment by mondersky** [comment]
I addressed this issue in the last release, if the issue still persist please let me know.

**Comment by anakinsleftleg** [comment]
This issue still persists. Nothing has changed. Maybe it only works on User installs of VScode and not on ALL USERS installs (where it goes in the /program files/ directory). i dont know but it doesn't work.

**Comment by oskarkk** [comment]
I'm using Tabs color v0.1.20 on VS Code 1.69.2 on Debian 11 and I had this error:

```
Tabscolor was unable to write to /usr/share/code/resources/app/out/bootstrap-window.js
```

I fixed it in a way that's kinda stupid but it worked: `sudo chmod a+w bootstrap-window.js`. After restarting VS Code the extension started working and I could remove that write permission and it still working correctly.

**Comment by mondersky** [comment]
thanks for sharing this with us, glad you managed to make it work. I am confused though because the extension is supposed to execute a chmod on the file to allow writing to it 
https://github.com/mondersky/tabscolor-vscode/blob/d2809556cabb66e12f8b514d96f344a9fd3a0a3d/extension.js#L128
anyways, I'll debug this further

**Comment by cjauvin** [comment]
I did some research and I've come to the conclusion that it's hopeless when running VSC in a snap package, in particular, because the filesystem is made to be readonly, and using `sudo chmod` won't cut it. A possible mitigation would be to detect this situation (when the location of the `workbench.desktop.main.js` file starts with `/snap/` for instance), and gracefully fail to install or run the extension, showing a clear error message.
