### ISSUE TITLE
Extension fails to activate on WSL

### ISSUE THREAD

**Issue by joelboersma** [mondersky/tabscolor-vscode#3]
In WSL, when I right-click on tabs, I see the "Color" option with all the different colors that can be selected. But clicking on one will do nothing.

After digging further, it seems the extension fails to activate when I'm using WSL. The extension functions as expected when working in a Windows directory.

I am running Windows 10 Home 21H1 and have Ubuntu 20.04 LTS running in WSL 2.

```log
[2022-07-01 21:21:46.971] [exthost] [info] ExtensionService#_doActivateExtension mondersky.tabscolor, startup: false, activationEvent: 'onStartupFinished'
[2022-07-01 21:21:47.329] [exthost] [info] Eager extensions activated
[2022-07-01 21:21:47.432] [exthost] [error] Activating extension mondersky.tabscolor failed due to an error:
[2022-07-01 21:21:47.432] [exthost] [error] Error: ENOENT: no such file or directory, open '/home/jboersma/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/bootstrap-window.js'
	at Object.openSync (node:fs:585:3)
	at Object.readFileSync (node:fs:453:35)
	at new Core (/home/jboersma/.vscode-server/extensions/mondersky.tabscolor-0.1.5-linux-x64/extension.js:67:23)
	at activate (/home/jboersma/.vscode-server/extensions/mondersky.tabscolor-0.1.5-linux-x64/extension.js:290:18)
	at Function._callActivateOptional (/home/jboersma/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:88:17470)
	at Function._callActivate (/home/jboersma/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:88:17131)
	at /home/jboersma/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:88:14945
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async S._activate (/home/jboersma/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:83:8180)
	at async S._waitForDepsThenActivate (/home/jboersma/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:83:8122)
	at async S._initialize (/home/jboersma/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:83:7486)
```

**Comment by mondersky** [comment]
thanks for reporting this, I have added a fix in the latest release, please let me know if the issue persists

**Comment by joelboersma** [comment]
I'm still getting a very similar error while running on extension version 0.1.20 :(

```
[2022-07-19 17:19:59.029] [exthost] [info] ExtensionService#_doActivateExtension mondersky.tabscolor, startup: false, activationEvent: 'onStartupFinished'
[2022-07-19 17:19:59.180] [exthost] [info] Eager extensions activated
[2022-07-19 17:19:59.323] [exthost] [error] Activating extension mondersky.tabscolor failed due to an error:
[2022-07-19 17:19:59.324] [exthost] [error] Error: ENOENT: no such file or directory, open '/home/jboersma/.vscode-server/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/bootstrap-window.js'
	at Object.openSync (node:fs:585:3)
	at Object.readFileSync (node:fs:453:35)
	at new Core (/home/jboersma/.vscode-server/extensions/mondersky.tabscolor-0.1.20-linux-x64/extension.js:67:23)
	at activate (/home/jboersma/.vscode-server/extensions/mondersky.tabscolor-0.1.20-linux-x64/extension.js:309:18)
	at Function._callActivateOptional (/home/jboersma/.vscode-server/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:97:17470)
	at Function._callActivate (/home/jboersma/.vscode-server/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:97:17131)
	at /home/jboersma/.vscode-server/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:97:14945
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async w._activate (/home/jboersma/.vscode-server/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:85:8180)
	at async w._waitForDepsThenActivate (/home/jboersma/.vscode-server/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:85:8122)
	at async w._initialize (/home/jboersma/.vscode-server/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:85:7486)
```

**Comment by riwarek** [comment]
Confirm this issue. I have WSL Ubuntu 22.04.
When something is wrong under windows I see message (like, TabColor couldn't do something). But under WSL there is even no notification something gone wrong.
I can just choose color from menu, nothing happen and thats all.

**Comment by Kattjakt** [comment]
Try adding the following to your `settings.json`:
```json
  "remote.extensionKind": {
    "mondersky.tabscolor": ["ui"]
  }
```

**Comment by pep248** [comment]
> Try adding the following to your `settings.json`:
> 
> ```json
>   "remote.extensionKind": {
>     "mondersky.tabscolor": ["ui"]
>   }
> ```

Didn't work for me.

**Comment by mondersky** [comment]
Test the latest update (version 0.2.4). I've implemented a fix for this issue. However, I've only tested it on Ubuntu. Please let me know if you encounter the same issue after applying the update

**Comment by pep248** [comment]
> Test the latest update (version 0.2.4). I've implemented a fix for this issue. However, I've only tested it on Ubuntu. Please let me know if you encounter the same issue after applying the update

Works like a charm! Thanks a lot!

**Comment by mondersky** [comment]
you're welcome
